CREATE TABLE RM556779.FUNCAO (
    id NUMBER(19) GENERATED AS IDENTITY,
    nome VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_FUNCAO PRIMARY KEY (id),
    CONSTRAINT CK_FUNCAO_NOME CHECK (nome IN ('ADMIN','GERENTE'))
);

CREATE TABLE RM556779.USUARIO (
    id NUMBER(19) GENERATED AS IDENTITY,
    img_perfil VARCHAR2(255),
    nome_perfil VARCHAR2(255),
    senha VARCHAR2(255),
    username VARCHAR2(255),
    CONSTRAINT PK_USUARIO PRIMARY KEY (id)
);

CREATE TABLE RM556779.USUARIO_FUNCAO_TAB (
    id_funcao NUMBER(19) NOT NULL,
    id_usuario NUMBER(19) NOT NULL,
    CONSTRAINT PK_USUARIO_FUNCAO PRIMARY KEY (id_funcao, id_usuario),
    CONSTRAINT FK_USU_FUNCAO_FUNC FOREIGN KEY (id_funcao) REFERENCES RM556779.FUNCAO(id),
    CONSTRAINT FK_USU_FUNCAO_USER FOREIGN KEY (id_usuario) REFERENCES RM556779.USUARIO(id)
);

CREATE TABLE RM556779.ENDERECO (
    id NUMBER(19) GENERATED AS IDENTITY,
    logradouro VARCHAR2(255) NOT NULL,
    numero NUMBER(10) NOT NULL,
    bairro VARCHAR2(100) NOT NULL,
    cidade VARCHAR2(100) NOT NULL,
    estado VARCHAR2(2) NOT NULL,
    cep VARCHAR2(9) NOT NULL,
    complemento VARCHAR2(255),
    CONSTRAINT PK_ENDERECO PRIMARY KEY (id)
);

CREATE TABLE RM556779.FILIAL (
    id NUMBER(19) GENERATED AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    fk_endereco NUMBER(19) NOT NULL,
    CONSTRAINT PK_FILIAL PRIMARY KEY (id),
    CONSTRAINT FK_FILIAL_ENDERECO FOREIGN KEY (fk_endereco) REFERENCES RM556779.ENDERECO(id)
);

CREATE TABLE RM556779.MOTO (
    id NUMBER(19) GENERATED AS IDENTITY,
    placa VARCHAR2(7) NOT NULL,
    ano NUMBER(10) NOT NULL,
    modelo VARCHAR2(50) NOT NULL,
    tipo_combustivel VARCHAR2(50) NOT NULL,
    fk_filial NUMBER(19) NOT NULL,
    CONSTRAINT PK_MOTO PRIMARY KEY (id),
    CONSTRAINT FK_MOTO_FILIAL FOREIGN KEY (fk_filial) REFERENCES RM556779.FILIAL(id)
);

CREATE TABLE RM556779.FUNCIONARIO (
    id NUMBER(19) GENERATED AS IDENTITY,
    nome VARCHAR2(150) NOT NULL,
    fk_filial NUMBER(19) NOT NULL,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (id),
    CONSTRAINT FK_FUNCIONARIO_FILIAL FOREIGN KEY (fk_filial) REFERENCES RM556779.FILIAL(id)
);